easy_admin:
  design:
    menu:
      - label: 'Blog'
        icon: 'newspaper-o'
        children:
          - {entity: 'Post', icon: 'newspaper-o', label: 'Articles'}
          - {entity: 'Category', icon: 'inbox', label: 'Catégories'}
          - {entity: 'Tag', icon: 'tags', label: 'Tags'}